### ISSUE TITLE
Add-VMGpuPartitionAdapter : 找不到与参数名称“InstancePath”匹配的参数。

### ISSUE THREAD

**Issue by pzzmyc** [seflerZ/oneclick-gpu-pv#1]
![屏幕截图 2023-04-14 145304](https://user-images.githubusercontent.com/43562427/231966544-23384900-5efa-4496-a442-2f7aba2d9bab.png)

**Comment by seflerZ** [comment]
InstancePath 即 GPU 的硬件地址，这个是通过 “Get-PnpDevice -Class Display -Status OK” 命令获取的，某种情况下操作系统会在前多加一个前缀，可以通过使用 "Get-VMHostPartitionableGpu" 观察 Name 一栏，来看看有什么区别，然后做对应修改即可。

**Comment by pzzmyc** [comment]
> InstancePath 即 GPU 的硬件地址，这个是通过 “Get-PnpDevice -Class Display -Status OK” 命令获取的，某种情况下操作系统会在前多加一个前缀，可以通过使用 "Get-VMHostPartitionableGpu" 观察 Name 一栏，来看看有什么区别，然后做对应修改即可。

真是奇怪，提示没有这个命令，但是powershell文档里面是有这个命令的，我换成了win11也是一样的结果，大佬有什么头猪吗
![屏幕截图 2023-04-14 181923](https://user-images.githubusercontent.com/43562427/232018830-4d5bb1bc-db66-4b09-89b6-dfa99eb09be5.png)
![屏幕截图 2023-04-14 182016](https://user-images.githubusercontent.com/43562427/232018848-12e3933f-6a95-4cff-96a4-b18baa6997fe.png)

**Comment by seflerZ** [comment]
我使用的是 WIN11 与 WIN10 ，都是有这个命令的，确认一下是否是专业版，然后安装原版。

**Comment by iSteveyang** [comment]
> > InstancePath 即 GPU 的硬件地址，这个是通过 “Get-PnpDevice -Class Display -Status OK” 命令获取的，某种情况下操作系统会在前多加一个前缀，可以通过使用 "Get-VMHostPartitionableGpu" 观察 Name 一栏，来看看有什么区别，然后做对应修改即可。
> 
> 真是奇怪，提示没有这个命令，但是powershell文档里面是有这个命令的，我换成了win11也是一样的结果，大佬有什么头猪吗 ![屏幕截图 2023-04-14 181923](https://user-images.githubusercontent.com/43562427/232018830-4d5bb1bc-db66-4b09-89b6-dfa99eb09be5.png) ![屏幕截图 2023-04-14 182016](https://user-images.githubusercontent.com/43562427/232018848-12e3933f-6a95-4cff-96a4-b18baa6997fe.png)

另一个版本说win11适用，直接删除掉-instance以及后面就可以了
https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/5#issuecomment-978985033

**Comment by wolibai** [comment]
好像win10 22H2没有 -InstancePath 参数，如果想添加其他显卡可以试试这样
多次用Add-VMGpuPartitionAdapter -VMName $vm命令，应该可以添加其他显卡，然后把不需要的删掉

# 添加虚拟显卡
|命令|解释|
|-----|----|
|$vm="name"|要修改的虚拟机名|
|Get-VMPartitionableGpu|获取你的支持虚拟的cpu清单，最新系统使用Get-VMHostPartitionableGpu获取|
|Add-VMGpuPartitionAdapter -VMName $vm|添加虚拟显卡，可多次添加，直到有自己想要的|
|Set-VMGpuPartitionAdapter -VMName $vm|自动设置虚拟显卡|
|Set-VM -VMName $vm -GuestControlledCacheTypes $true -LowMemoryMappedIoSpace 1GB -HighMemoryMappedIoSpace 10GB||

----------------

# 如果添加了多张虚拟显卡，可删除多余的
|命令|解释|
|---|---|
|~~Remove-VMGpuPartitionAdapter -VMName $vm~~|删除全部虚拟显卡，重新操作可用此命令|
|$testvm = Get-VM $vm|要修改的虚拟机名|
|Get-VMGpuPartitionAdapter -VM $testvm|获取虚拟机的信息，里面包含虚拟显卡ID|
|Remove-VMGpuPartitionAdapter -VM $testvm -AdapterId "ID"|ID里填写上面命令里获取到的ID|
### 以上命令请按自己需求进行删改
