### ISSUE TITLE
dxgkrnl dkms模块编译失败

### ISSUE THREAD

**Issue by LionTao** [seflerZ/oneclick-gpu-pv#2]
我在Ubuntu22.04.2上对kernel5.19进行dkms编译的时候失败了，是不是对内核版本有一定要求呀？

**Comment by seflerZ** [comment]
> 我在Ubuntu22.04.2上对kernel5.19进行dkms编译的时候失败了，是不是对内核版本有一定要求呀？

我使用的是 5.15，这类东西建议不要太超前，用中位数的就行，不然配套的容易跟不上。
